name = "secure-dns-worker"
type = "javascript"
account_id = "your_account_id_here"
workers_dev = true
compatibility_date = "2023-08-29"

# 构建和发布配置
build = {
  command = "npm run build",
  cwd = "./",
  watch_dir = "./"
}

# 配置 Worker 的部署环境
[env.production]
name = "secure-dns-worker-prod"
route = "https://secure-dns.example.com/*"
zone_id = "your_zone_id_here"

# 默认的 KV Namespace，适用于缓存和其他数据存储
kv_namespaces = [
  { binding = "DNS_CACHE", id = "your_kv_namespace_id_here" }
]

# 环境变量设置，使用 SECRET_KEY 进行加密操作
[vars]
SECRET_KEY = "your_secret_key_here"

# 开发环境下的设置
[env.dev]
name = "secure-dns-worker-dev"
route = ""
workers_dev = true

# 执行 wrangler publish 的时候，启用以下钩子来运行测试或进行构建等
[build.upload]
format = "service-worker"

# 使用服务绑定（如有需要）
[[services]]
name = "your_service_name_here"
service = "your_service_name_here"
environment = "your_service_environment_here"

# 其他设置 (如有)
[durable_objects]
bindings = []
