name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Publish to Cloudflare Workers
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # Ensure you have added this secret in your GitHub repo settings
      run: npm run deploy

    - name: Publish to Cloudflare Workers
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # Ensure you have added this secret in your GitHub repo settings
      run: npm run deploy
